name: Build Image from Dockerfile

on:
  workflow_dispatch:
  schedule:
  #        ┌───────────── minute (0 - 59)
  #        │ ┌───────────── hour (0 - 23)
  #        │ │ ┌───────────── day of the month (1 - 31)
  #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #        │ │ │ │ │
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build_image:
    name: Build ${{ matrix.platform }} image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [manylinux2014_x86_64, manylinux2014_aarch64]

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      if: matrix.platform == 'manylinux2014_aarch64'
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64

    - name: Publish Image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        imageName: ${{ matrix.platform }}-qmflows
        containerRegistry: true
        contextName: ./manylinux2014.dockerfile
        buildArgs: |
          PLATFORM=${{ matrix.platform }}
