name: Build Image from Dockerfile

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build_x86_64_wheels:
    name: Build image for x86_64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Publish Image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        imageName: manylinux2014_x86_64-qmflows
        containerRegistry: true
        contextName: ./x86_64.dockerfile
